modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/jaredlll08/searchables/issues"
license = "MIT"

[[mods]]
modId = "searchables"
updateJSONURL = "https://updates.blamejared.com/get?n=searchables&gv=1.19.3"
version = "${file.jarVersion}"
displayName = "Searchables"
displayURL = "https://minecraft.curseforge.com/projects/searchables"
authors = "Jaredlll08"
logoFile = "icon.png"
description = '''
A library mod to facilitate adding search bars with auto complete and search types.
'''
itemIcon = "minecraft:compass"
[[dependencies.searchables]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
[[dependencies.searchables]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"